version: "3.8"

services:
  shadowsocks-server:
    build: .
    ports:
      - 443:443
      - 443:443/udp
    volumes:
      - ./server.json:/server.json
    command: [ "ssserver", "-c","/server.json","-u"]
    restart: always
    container_name: ssserver
